#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

export DATA_FILE="${DATA_FILE:-/tmp/async-order-users-formal.csv}"
export REPORT_ROOT="${REPORT_ROOT:-$ROOT_DIR/reports/jmeter-soldout-flood}"
export HEAP="${HEAP:--Xms512m -Xmx2g -XX:MaxMetaspaceSize=256m}"

# 售罄洪峰只压下单入口。结果轮询会把查询压力混进去，影响入口削峰判断。
export POLL_RESULT="${POLL_RESULT:-false}"

REQUESTS="${REQUESTS:-300000}"
STOCK_QUANTITY="${STOCK_QUANTITY:-3000}"
ORDER_QUANTITY="${ORDER_QUANTITY:-2}"
USER_MULTIPLIER="${USER_MULTIPLIER:-4}"
EXPECTED_SUCCESS_ORDERS=$((STOCK_QUANTITY / ORDER_QUANTITY))
EXPECTED_LOAD_USERS=$((STOCK_QUANTITY * USER_MULTIPLIER))
export DURATION_SECONDS="${DURATION_SECONDS:-60}"
export TARGET_QPS="${TARGET_QPS:-$(((REQUESTS + DURATION_SECONDS - 1) / DURATION_SECONDS))}"
export THREADS="${THREADS:-800}"
export RAMP_SECONDS="${RAMP_SECONDS:-1}"

EXPECTED_REQUESTS=$((TARGET_QPS * DURATION_SECONDS))

cat <<CONFIG
Smart Ticket 售罄洪峰压测
目标语义：少量库存 + 海量入口请求 + 大量重复用户尝试 + Redis/Kafka 削峰 + 最终订单不超过库存
STOCK_QUANTITY=$STOCK_QUANTITY
ORDER_QUANTITY=$ORDER_QUANTITY
EXPECTED_SUCCESS_ORDERS=$EXPECTED_SUCCESS_ORDERS
USER_MULTIPLIER=$USER_MULTIPLIER
EXPECTED_LOAD_USERS=$EXPECTED_LOAD_USERS
REQUESTS=$REQUESTS
TARGET_QPS=$TARGET_QPS
DURATION_SECONDS=$DURATION_SECONDS
EXPECTED_REQUESTS=$EXPECTED_REQUESTS
THREADS=$THREADS
RAMP_SECONDS=$RAMP_SECONDS
POLL_RESULT=$POLL_RESULT
DATA_FILE=$DATA_FILE
CONFIG

if [[ "$EXPECTED_REQUESTS" -ne "$REQUESTS" ]]; then
  echo "注意：按 TARGET_QPS * DURATION_SECONDS 实际会打 $EXPECTED_REQUESTS 次，不是精确 $REQUESTS 次。"
fi

exec "$ROOT_DIR/scripts/load/run-async-order-jmeter.sh"
