@baseUrl = http://localhost:8081
@showId = 1
@sessionId = 1


### 1. 查询演出详情第一次：预计查询数据库并写入 Redis
GET {{baseUrl}}/api/shows/{{showId}}


### 2. 查询演出详情第二次：预计命中 show:detail:{{showId}}
GET {{baseUrl}}/api/shows/{{showId}}


### 3. 查询演出场次第一次：预计查询数据库并写入 Redis
GET {{baseUrl}}/api/shows/{{showId}}/sessions


### 4. 查询演出场次第二次：预计命中 show:sessions:{{showId}}
GET {{baseUrl}}/api/shows/{{showId}}/sessions


### 5. 查询场次票档第一次：预计查询数据库并写入 Redis
GET {{baseUrl}}/api/sessions/{{sessionId}}/ticket-categories


### 6. 查询场次票档第二次：预计命中 session:ticket-categories:{{sessionId}}
GET {{baseUrl}}/api/sessions/{{sessionId}}/ticket-categories
