package com.zewbby.smartticket.enums;

public enum AdminOperationTypeEnum {

    STOCK_INIT("STOCK_INIT"),
    STOCK_ADJUST("STOCK_ADJUST"),
    STOCK_PREHEAT("STOCK_PREHEAT"),
    STOCK_REPAIR("STOCK_REPAIR"),
    STOCK_CONSISTENCY_IGNORE("STOCK_CONSISTENCY_IGNORE"),
    LOCAL_MESSAGE_RETRY("LOCAL_MESSAGE_RETRY"),
    LOCAL_MESSAGE_MARK_DEAD("LOCAL_MESSAGE_MARK_DEAD"),
    DEAD_LETTER_RETRY("DEAD_LETTER_RETRY"),
    DEAD_LETTER_IGNORE("DEAD_LETTER_IGNORE"),
    DEAD_LETTER_RESOLVE("DEAD_LETTER_RESOLVE"),
    ORDER_REQUEST_COMPENSATE("ORDER_REQUEST_COMPENSATE"),
    SHOW_CREATE("SHOW_CREATE"),
    SHOW_UPDATE("SHOW_UPDATE"),
    SHOW_PUBLISH("SHOW_PUBLISH"),
    SHOW_OFFLINE("SHOW_OFFLINE"),
    SESSION_CREATE("SESSION_CREATE"),
    SESSION_UPDATE("SESSION_UPDATE"),
    SESSION_PUBLISH("SESSION_PUBLISH"),
    SESSION_OFFLINE("SESSION_OFFLINE"),
    TICKET_CATEGORY_CREATE("TICKET_CATEGORY_CREATE"),
    TICKET_CATEGORY_UPDATE("TICKET_CATEGORY_UPDATE"),
    TICKET_CATEGORY_PUBLISH("TICKET_CATEGORY_PUBLISH"),
    TICKET_CATEGORY_OFFLINE("TICKET_CATEGORY_OFFLINE");

    private final String code;

    AdminOperationTypeEnum(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
